// <auto-generated />
using System;
using System.Collections.Generic;
using Email.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Email.Api.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20260422033036_UpdateTablePending")]
    partial class UpdateTablePending
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Email.Api.Entities.Emails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("integer");

                    b.Property<string>("EmailText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastErrorMsg")
                        .HasColumnType("text");

                    b.Property<int>("ReciveUserNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Emails", "public");
                });

            modelBuilder.Entity("Email.Api.Entities.TasksEmailsPending", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstEventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<int>>("PendingTaskNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("PlanSentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReciveUserNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TaskTitles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TasksEmailsPending", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
