// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Api.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260415125336_UpdateUserIdToNumber")]
    partial class UpdateUserIdToNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notification.Api.Entities.Notifications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("FromUserNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystemMsg")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("MsgText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MsgTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MsgTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications", "public");
                });

            modelBuilder.Entity("Notification.Api.Entities.Notifications_Dtl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MainId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReciveUserNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("readTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications_Dtl", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
