// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Query.Api.Data;

#nullable disable

namespace Query.Api.Migrations
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20260415125122_UpdateUserIdToNumber")]
    partial class UpdateUserIdToNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Query.Api.Entities.TaskCommentRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskCommentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<int>("UserNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskCommentRead", "public");
                });

            modelBuilder.Entity("Query.Api.Entities.TaskEmailSummaryRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReciveUserNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TaskEmailSummaryRead", "public");
                });

            modelBuilder.Entity("Query.Api.Entities.TaskModifyLineRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModifyUserNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskOperatesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TaskModifyLineRead", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
